### ISSUE TITLE
小屏时 drawer 没有适配，显示错位

### ISSUE THREAD

**Issue by BiKibb** [umijs/ant-design-pro#6]
## bug 演绎步骤

1. 根据教程：【[通过脚手架创建项目](https://umijs.org/zh/guide/create-umi-app.html#%E5%88%9B%E5%BB%BA-umi-%E9%A1%B9%E7%9B%AE)】 的 `yarn create umi` => `ant-design-pro` 新建一个项目
2. 通过 `yarn` 安装好依赖后，直接在没有任何修改的新项目运行 `yarn start`
3. 这时候调整窗口大小，可以看到，左侧的 drawer 显示错位

![snipaste_2019-02-24_00-28-03](https://user-images.githubusercontent.com/32301377/53289001-b2d98780-37cb-11e9-9d68-9bd8a0ed648e.png)

## 情况描述

检查 drawer 的 padding 属性，可以初步得知是因为 padding 值设为了 24

![显示错乱](https://user-images.githubusercontent.com/32301377/53288940-2ed2d000-37ca-11e9-8bbb-6ef42b24bf51.png)

在 `src\components\SiderMenu\index.less` 中的 `:global` 全局样式中设置 padding 为 0 后恢复正常

```css
:global {
  ...
 .ant-drawer-left {
    .ant-drawer-body {
      padding: 0;
    }
  }
}
```

![修复后](https://user-images.githubusercontent.com/32301377/53288959-8c671c80-37ca-11e9-9f0a-5ea1280d71eb.png)
